### PR TITLE
Added Who, What & Duration fields + some UI cleanup

### PR DESCRIPTION
**Pull request by nilsjesper**
I realize this may be a lot for one PR but I made some edits to this project to make it suitable for my own reporting needs and I thought some of these changes might be welcome in the main project.  I thought "Who" and "What" were a little more generic than "Client" & "Project".

I examined using a formula in google sheets  `=MROUND(indirect("b" & row()) - indirect("A" & row()),"0:15")` to generate the duration but couldn't get it quite right.

Screenshot of formatting: 
image

I realize the formatting may now be slightly more US-centric but I thought at least by removing seconds from the displays and inputs it'd be a little more useable.

Timesheets are my kryptonites and these updates have made this project a lifesaver so far.

Open to all feedback and changes.

### CODE REVIEW

**Comment by nilsjesper** [comment]
Hi @anvaka - have been using this fork daily and it's been great so if nothing else, I just wanted to say thanks. But curious if you had any thoughts on this PR.

**Comment by anvaka** [comment]
Hi Martin!

I think this is very cool! I realize there are different usage patterns for time tracking tools, and there is definitely value in your fork. 

I was thinking about making this tool more generic, without being necessary bound to one or another column layout. For example, instead of hardcoding column named `who`, maybe there is a way for this tool to fetch information about available columns in the sheet, and just map them to edit fields? 

That way if someone needs to add different columns (e.g. `who`, or `billable`) - the UI could read columns from the sheets, parse information about their format, and based on that make smart choices to render corresponding input fields (time input, checkbox, etc.)

There is also a way to count duration in Google Sheets itself with proper formatting (set field value to `=B2-A2`, and in the format options choose `Number->Duration`). Fields like this shouldn't be editable, maybe Sheets API provide meta-information, that could be parsed?

Anyway, those are my thoughts. Do you have it running somewhere publicly, so I could share link to your fork?

**Comment by nilsjesper** [comment]
Hi Andrei - somehow I totally missed the notification that you'd responded!  Sorry about that.

I think you're right that allowing for **configurable columns** would be great, I just wasn't sure how you'd thought about handling configuration overall so I went the hard-coded route!  But I think that'd be a fun improvement to make.  I suppose the best configuration would be a sheet-by-sheet option, right?  Would probably make sense to set those options when the sheet is CREATED so that there aren't complexities with updating this "schema" later on.

As far as **duration**, I was able to get this working as a formula first : `=MROUND(indirect("b" & row()) - indirect("A" & row()),"0:15")` but I was having some trouble setting things up correctly to create this column on each save AND to return the time as duration ( eg 1:00:00 instead of "0.04166666667").  BUT, I'm sure that's a solvable problem so let me see if I can put a little extra time into it.

For me, though **rounding** to the quarter hour is a must but maybe that's yet another configuration it would make sense to allow users to set? Any opinions there?

I had wanted to try getting this up and running live but I haven't been able to get the Google App permissions set up correctly, it seems. Is there any way you could share what your settings are? At the moment, I'm just testing (and using) this on localhost using the key that was in your fork.

Anyway, let me see what I can do about the suggestions above. At a minimum, I'm hoping the formula update should be pretty straightforward.  Would love to hear your thoughts on what the best configuration mechanism would be.

Thanks again for a great project.

**Comment by nilsjesper** [comment]
Alright, made some minor tweaks so that the duration can now be calculated by the spreadsheet itself.  I removed the changes I'd made to the columns until a way can be figured out to do that via configuration.  

You can check out my fork in action here: https://motimetracker.appspot.com/

**Comment by nilsjesper** [comment]
@anvaka Started hacking a little bit on the custom fields work but the auto-generated durations seem to be working just fine!  Be curious to see if you have any other feedback.

**Pull request closed without merging**
